application: unmung2
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /images
  static_dir: images
- url: /static
  static_dir: static
- url: /.*
  script: unmung.application

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]